services:
  recsys-api:
    build: .
    container_name: recsys-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    restart: unless-stopped

  # MLflow для трекинга экспериментов
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.13.0
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_ALLOW_DNS_REBINDING=true
    volumes:
      - mlflow_data:/mlflow
    command: ["mlflow", "server", "--host", "0.0.0.0", "--allowed-hosts", "localhost:5000,mlflow:5000", "--backend-store-uri", "sqlite:///mlflow/mlflow.db", "--default-artifact-root", "/mlflow/artifacts"]

  # Prometheus — сбор метрик
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  # Grafana — визуализация метрик
  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    restart: unless-stopped

volumes:
  mlflow_data:
  grafana_data:
