[flake8]
max-line-length = 120
max-complexity = 10
ignore = 
    W293,  # blank line contains whitespace
    W291,  # trailing whitespace
    E302,  # expected 2 blank lines
    E305,  # expected 2 blank lines after class/function
    E261,  # at least two spaces before inline comment
    E265,  # block comment should start with '# '
    W292,  # no newline at end of file
    F401,  # imported but unused (DS-специфика)
    E501,  # line too long (увеличили до 120)
